[package]
name = "learn_more_rust"
version = "0.1.0"
authors = ["Bernard Igiri <bernard.igiri@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"
glam = "0.9.3"
